name: AutoTwttelgrm4

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 999

    steps:
    - name: Instala Paquetes Necesarios
      run: |
        cmd /c pip install requests
        cmd /c pip install m3u8
        cmd /c pip install aiohttp
        cmd /c pip install telegram-upload
        cmd /c md "C:\1Twitch"
        cmd /c md "C:\Users\runneradmin\.config"
    - name: Descargar Archivos Necesarios
      run: |
        Invoke-WebRequest https://drive.google.com/uc?id=$Env:SESSION_DATA -OutFile "C:\Users\runneradmin\.config\data.zip"
        Invoke-WebRequest https://raw.githubusercontent.com/vgcrdv/AutoTwttelgrm4/main/DuplTwi_R0_1_var.py -OutFile "C:\1Twitch\DuplTwi_R0_1_var.py"
        Invoke-WebRequest https://raw.githubusercontent.com/vgcrdv/AutoTwttelgrm4/main/DuplTwi_R0_1.py -OutFile "C:\1Twitch\DuplTwi_R0_1.py"
      env:
        SESSION_DATA: ${{ secrets.SESSION_DATA_4 }}
    - name: Descomprimir Datos
      run: |
        cd "C:\Users\runneradmin\.config"
        Expand-Archive data.zip -DestinationPath "C:\Users\runneradmin\.config"
    - name: Ejecutar
      run: |
        cd "C:\1Twitch"
        python DuplTwi_R0_1.py $Env:CHNLS_LINKS 1408710707,1408641267,1408825440
      env:
        CHNLS_LINKS: ${{ secrets.CHNLS_LINKS }}
